Add makepkg option - optional basic check that PKGBUILD could be built
KSXGitHub/github-actions-deploy-aur pull request #31
Opened 2022-08-09 08:41 UTC by rgeraskin

It'll be handy to be able to check that `makepkg` passed without errors before packaging and deploying new release. E.g., file names or paths in the source archive could be changed. And with such "test build" we could catch failed pkg before releasing.

This check is optional. Also, `makepkg` is launched with `--nodeps` option for simplicity.

2022-08-09 08:46 UTC, KSXGitHub requested changes
Also, please update README.md

2022-08-09 08:46 UTC, KSXGitHub commented on action.yml
> +    description: 'Build package using `makepkg` before deploy'
```suggestion
  test:
    description: 'Check that PKGBUILD could be built'
```

2022-08-09 08:46 UTC, KSXGitHub commented on build.sh
> +makepkg=$INPUT_MAKEPKG
```suggestion
test=$INPUT_TEST
```

2022-08-09 08:46 UTC, KSXGitHub commented on build.sh
> +if [ "$makepkg" == "true" ]; then
```suggestion
if [ "$test" == "true" ]; then
```

2022-08-09 10:16 UTC, rgeraskin commented on build.sh
> +if [ "$makepkg" == "true" ]; then
done

2022-08-09 10:16 UTC, rgeraskin commented on build.sh
> +makepkg=$INPUT_MAKEPKG
done

2022-08-09 10:16 UTC, rgeraskin commented on action.yml
> +    description: 'Build package using `makepkg` before deploy'
done

2022-08-09 10:17 UTC, rgeraskin commented
@KSXGitHub I've renamed makepkg to 'test' and updated readme also

2022-08-10 10:00 UTC, rgeraskin commented
@KSXGitHub I use it in my workflows, [here](https://github.com/rgeraskin/aur-werf-bin/runs/7755133296?check_suite_focus=true) you can see yesterday workflow run. Look at `Publish AUR package` step.

2022-08-10 10:03 UTC, KSXGitHub approved these changes
Perfect! Thank you.

2022-08-10 10:03 UTC, merged

2022-08-10 10:07 UTC, KSXGitHub commented
[v2.5.0](https://github.com/KSXGitHub/github-actions-deploy-aur/releases/tag/v2.5.0)